#!/usr/bin/env ruby

Dir[File.join File.dirname(__FILE__), 'lib', '*.rb'].each do |file|
  require file
end

require "matrix"
require "graphviz"
require "csv"
require 'erb'

require "#{Dir.pwd}/test/andtest.rb"
